name: Feature request
description: Suggest an idea
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like FireTube to do?
      description: Describe the problem it solves, not just the solution.
    validations:
      required: true
