"""Builds the Home header's wordmark: the flame plus "FireTube" as vector paths.

Writes two drawables with the same viewport, drawn on top of each other:
- drawable/wordmark_flame.xml: the launcher flame with its brand gradient.
- drawable/wordmark_letters.xml: the letters in white, tinted at runtime with the app theme's
  onSurface (a color resource would follow the system's night mode, not FireTube's own theme
  setting, and could go dark-on-dark).

The letters are Poppins Bold (SIL Open Font License 1.1), converted to outlines so the app ships
no font file. To rebuild (the font is pinned; the script checks its SHA-256):

    python -m pip install fonttools uharfbuzz
    curl -LO https://github.com/google/fonts/raw/7dc16b7de42db624b902f2292b68ed9e489e5053/ofl/poppins/Poppins-Bold.ttf
    python tools/make_wordmark.py Poppins-Bold.ttf
"""
import hashlib
import sys
from pathlib import Path

import uharfbuzz as hb
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

FONT_SHA256 = "983676516167748b74de6f4771fb384c664fd913acb8b471122ecacf5da5ea6c"
TEXT = "FireTube"
HEIGHT = 64.0  # viewport height; the drawable is HEIGHT dp tall at scale 1
CAP = 34.0  # cap height of the letters, in viewport units
BASELINE = 47.0  # y of the text baseline
GAP = 6.0  # space between flame and text

# The launcher foreground's flame (drawable/ic_launcher_foreground.xml), in its 108-unit viewport.
FLAME = (
    "M56,27 C68,40 74,55 71,68 C69,78 62,83 54.5,83 C46.5,83 40,77.5 39.5,70 "
    "C39,62.5 45,56.5 50.5,51 C55,46.5 57.5,38 56,27 Z "
    "M54.5,63 A9,9 0 1,0 54.5,81 A9,9 0 1,0 54.5,63 Z"
)
FLAME_BOX = (39.5, 27.0, 74.0, 83.0)  # x0, y0, x1, y1
FLAME_HEIGHT = 57.0
FLAME_TOP = 1.0


def text_path(font_path: str) -> tuple[str, float]:
    """The text's outline as one SVG path in viewport units (y down), and its advance width."""
    blob = hb.Blob.from_file_path(font_path)
    hb_font = hb.Font(hb.Face(blob))
    buf = hb.Buffer()
    buf.add_str(TEXT)
    buf.guess_segment_properties()
    hb.shape(hb_font, buf, {"kern": True, "liga": False})

    font = TTFont(font_path)
    glyphs = font.getGlyphSet()
    order = font.getGlyphOrder()
    cap_height = font["OS/2"].sCapHeight
    scale = CAP / cap_height

    pen = SVGPathPen(glyphs, ntos=lambda v: f"{v:.2f}".rstrip("0").rstrip("."))
    x = 0
    for info, pos in zip(buf.glyph_infos, buf.glyph_positions):
        name = order[info.codepoint]
        # font units, y up -> viewport units, y down, origin at the baseline
        glyphs[name].draw(TransformPen(pen, (scale, 0, 0, -scale, (x + pos.x_offset) * scale, 0)))
        x += pos.x_advance
    return pen.getCommands(), x * scale


def main() -> None:
    font_path = sys.argv[1] if len(sys.argv) > 1 else "Poppins-Bold.ttf"
    digest = hashlib.sha256(Path(font_path).read_bytes()).hexdigest()
    if digest != FONT_SHA256:
        sys.exit(f"{font_path} isn't the pinned Poppins Bold (sha256 {digest}); see the docstring")
    letters, text_width = text_path(font_path)

    x0, y0, x1, y1 = FLAME_BOX
    flame_scale = FLAME_HEIGHT / (y1 - y0)
    flame_width = (x1 - x0) * flame_scale
    text_x = flame_width + GAP
    width = text_x + text_width + 1

    header = f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/make_wordmark.py; edit that, not this. {{what}} -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="{width:.1f}dp" android:height="{HEIGHT:.0f}dp"
    android:viewportWidth="{width:.2f}" android:viewportHeight="{HEIGHT:.0f}">
"""
    flame = f"""    <group android:scaleX="{flame_scale:.4f}" android:scaleY="{flame_scale:.4f}"
        android:translateX="{-x0 * flame_scale:.3f}" android:translateY="{FLAME_TOP - y0 * flame_scale:.3f}">
        <path android:fillType="evenOdd" android:pathData="{FLAME}">
            <aapt:attr name="android:fillColor">
                <gradient android:type="linear"
                    android:startX="{x0}" android:startY="{y0}" android:endX="{x1}" android:endY="{y1}">
                    <item android:offset="0" android:color="@color/flame_start" />
                    <item android:offset="0.5" android:color="@color/brand_red" />
                    <item android:offset="1" android:color="@color/flame_end" />
                </gradient>
            </aapt:attr>
        </path>
    </group>
</vector>
"""
    text = f"""    <group android:translateX="{text_x:.3f}" android:translateY="{BASELINE:.3f}">
        <path android:fillColor="#FFFFFF" android:pathData="{letters}" />
    </group>
</vector>
"""
    drawables = Path(__file__).resolve().parent.parent / "app/src/main/res/drawable"
    for name, what, body in [
        ("wordmark_flame.xml", "The wordmark's flame; drawn under wordmark_letters.", flame),
        ("wordmark_letters.xml", "The wordmark's letters (Poppins Bold, OFL 1.1), white for tinting.", text),
    ]:
        (drawables / name).write_text(header.replace("{what}", what) + body, encoding="utf-8", newline="\n")
    print(f"wrote wordmark_flame.xml and wordmark_letters.xml ({width:.1f} x {HEIGHT:.0f} dp)")


if __name__ == "__main__":
    main()
